version: "3.7"

services:
    minio:
      image: minio/minio
      environment:
        - MINIO_CONSOLE_ADDRESS=:9001
        - MINIO_ROOT_USER=mlops
        - MINIO_ROOT_PASSWORD=mlops
      ports:
        - "9000:9000"
        - "9001:9001"
      command:
        - server
        - /data
      volumes:
        - minio-data:/data


    postgres:
      image: postgres
      environment:
        - POSTGRES_USER=mlops-db
        - POSTGRES_PASSWORD=mlops-db
        - POSTGRES_DB=mlops-db
        - PGDATA=/var/lib/postgresql/data
      ports:
        - "5432:5432"
      volumes:
        - mlflow-db-data:/var/lib/postgresql/data
    
    mlflow:
      build: "mlflow"
      environment:
        - MLFLOW_S3_ENDPOINT_URL=http://minio:9000/
        - AWS_ACCESS_KEY_ID=mlops
        - AWS_SECRET_ACCESS_KEY=mlops
      command: ["server","--host", "0.0.0.0", "--port", "9002", "--backend-store-uri","postgresql://mlops-db:mlops-db@postgres:5432/mlops-db", "--default-artifact-root","s3://mlops"]
      ports:
        - "9002:9002"
      depends_on:
        - minio
        - postgres


volumes:
  minio-data: 
  mlflow-db-data:
